import JotaiProvider from "@/providers/Jotai";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NuqsAdapter>
          <JotaiProvider>{children}</JotaiProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
