import JotaiProvider from "@/providers/Jotai";
import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ReactNode } from "react";
import "@/style/global.scss";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Shop Management",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NuqsAdapter>
          <JotaiProvider>
            {children}
            <ToastContainer
              position="bottom-right"
              theme="dark"
              autoClose={1500}
            />
          </JotaiProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
